# Generated by Django 5.1.1 on 2024-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_otp_otpexpriedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otpexpriedtime',
            field=models.CharField(max_length=50),
        ),
    ]
